- .travis.yml
Inspired by https://github.com/nickstenning/travis-pip-cache/blob/master/.travis.yml
```
Collecting coverage==4.4.1 (from indexdigest==0.1.0)
Using cached coverage-4.4.1-cp27-cp27mu-manylinux1_x86_64.whl
```
> Travis: use cache

- .pylintrc
- README.md
- indexdigest/__init__.py
- indexdigest/cli/__init__.py
- indexdigest/cli/script.py
- indexdigest/database.py
- indexdigest/linters/__init__.py
- indexdigest/linters/redundant_indices.py
- indexdigest/utils.py
- setup.py
```
$ index_digest mysql://index_digest:qwerty@localhost/index_digest
Found 2 issue(s) to report for "index_digest" database
redundant_indices | 0004_id_foo: UNIQUE KEY idx (id, foo) index can be removed as redundant (covered by PRIMARY KEY (id, foo))
redundant_indices | 0004_id_foo_bar: KEY idx_foo (foo) index can be removed as redundant (covered by KEY idx_foo_bar (foo, bar))
```
> Introduce index_digest command line tool

- indexdigest/linters/__init__.py
- indexdigest/linters/linter_0002_not_used_indices.py
- indexdigest/linters/linter_0019_queries_not_using_indices.py
- indexdigest/test/linters/test_0002_not_used_indices.py
- indexdigest/test/linters/test_0019_queries_not_using_indices.py
- sql/0019-queries-not-using-indices-log
> queries_not_using_index: handle no matching row in const table

- indexdigest/linters/linter_0004_redundant_indices.py
- indexdigest/test/linters/test_0004_redundant_indices.py
- sql/0004-redundant-indices.sql
> redundant_indices: avoid redundant indices being reported in a loop

- indexdigest/schema.py
- indexdigest/test/core/test_indices.py
- indexdigest/test/linters/test_0004_redundant_indices.py
- sql/0004-redundant-indices.sql
> Unique vs PK... Not necessarily redundant due to unique constraintprefer unique over non unique indices and primary keys over unique ones

- .travis.yml
Run all Python versions tests on MySQL 5.7, run all MySQL version tests on Python 3.6
It's **7 vs 24 jobs** run by Travis (in **13 vs 30 minutes**), thanks to https://docs.travis-ci.com/user/customizing-the-build/#Explicitly-Including-Jobs
> travis: make build matrix a bit smaller (and faster)

- indexdigest/cli/add_linter.py
- setup.py
```
$ add_linter 89 'empty_table'
INFO     Creating a new linter: 0089 - empty-table ...
INFO     Add SQL schema and log files (sql/0089-empty-table) ...
INFO     ... sql/0089-empty-table.sql created
INFO     ... sql/0089-empty-table-log created
INFO     Add Python code ...
INFO     ... indexdigest/linters/linter_0089_empty_table.py created
INFO     Add a test ...
INFO     ... indexdigest/test/linters/test_0089_empty-table.py created
```
> `id` is taken from GitHub issue - https://github.com/macbre/index-digest/issues/89
This creates the following files:
```
indexdigest/linters/linter_0089_empty_table.py
indexdigest/test/linters/test_0089_empty-table.py
sql/0089-empty-table-log
sql/0089-empty-table.sql
```
> add_linter helper script

- indexdigest/query.py
- indexdigest/test/core/test_query.py
Fixes https://github.com/macbre/query-digest/issues/16
> get_query_tables: improve SQL queries parsing

- indexdigest/linters/linter_0006_not_used_columns_and_tables.py
- indexdigest/test/linters/test_0006_not_used_columns_and_tables.py
- indexdigest/test/test_0089_handle_sql_errors.py
- sql/0098-handle-sql-errors-log
Use `sql_metadata.get_query_tables` instead of `EXPLAIN` query (that returns the table alias not its real name).
Example:
```sql
SELECT /* a comment */ foo FROM `0006_not_used_columns` AS r WHERE id = 1;
```
> Improve get_used_tables_from_queries handling of table aliases

- indexdigest/linters/linter_0028_data_too_old.py
Otherwise `check_data_not_updated_recently` and `check_data_too_old` will run these (possibly heavy) queries twice:
```sql
2018-02-02 12:39:24 indexdigest.database.query          INFO     SELECT /* index-digest */ UNIX_TIMESTAMP(MIN(`msg_date`)) as `min`, UNIX_TIMESTAMP(MAX(`msg_date`)) as `max` FROM messages_status
```
> get_boundary_times: add @memoize

- indexdigest/linters/linter_0028_data_too_old.py
- indexdigest/test/linters/test_0028_data_not_updated_recently.py
- indexdigest/test/linters/test_0028_data_too_old.py
- sql/0028-data-too-old.sql
```sql
data_not_updated_recently → table affected: 0028_revision
✗ "0028_revision" has the latest row added 69 days ago, consider checking if it should be up-to-date
- diff_days: 69
- data_since: 2018-01-01 00:00:00
- data_until: 2018-01-01 00:00:00
- date_column_name: rev_timestamp
- schema: CREATE TABLE `0028_revision` (
`rev_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`rev_timestamp` binary(14) NOT NULL,
PRIMARY KEY (`rev_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1
- rows: 1
- table_size_mb: 0.015625
```
Check MediaWiki tables columns that use `CHAR(14)` instead of `DATETIME` - [see why](https://phabricator.wikimedia.org/T164898#3302863).
> data-too-old: check columns with non-timestamp types, but with "time" in their names

- indexdigest/linters/linter_0028_data_too_old.py
```sql
2018-03-13 08:34:04 indexdigest.database.query          INFO     SELECT /* index-digest */ UNIX_TIMESTAMP(MIN(`created`)) as `min`, UNIX_TIMESTAMP(MAX(`created`)) as `max` FROM foo_bar-metadata
2018-03-13 08:34:04 indexdigest.database.query          ERROR    Database error #1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to 
```
> get_boundary_times | handle tables with dashes

- .gitignore
- .travis.yml
- Makefile
- README.md
- indexdigest/cli/script.py
- indexdigest/linters/__init__.py
- indexdigest/linters/linter_0164_empty_database.py
- indexdigest/test/linters/test_0028_data_not_updated_recently.py
- indexdigest/test/linters/test_0164_empty_database.py
- setup.sql
- sql/0028-data-not-updated-recently.sql
> Detect empty databases

- indexdigest/linters/linter_0019_queries_not_using_indices.py
- indexdigest/test/linters/test_0019_queries_not_using_indices.py
- sql/0019-queries-not-using-indices-log
> queries_not_using_index | handle "No tables used"

- .dockerignore
- Dockerfile
- Makefile
- README.md
Resolves #150
Example:
```
docker run --network=host -t macbre/index-digest:latest mysql://index_digest:qwerty@127.0.0.1/index_digest --analyze-data --skip-checks=non_utf_columns --skip-tables=0028_no_time
```
> Dockerize index-digest and push it to Docker Hub

- CONTRIBUTING.md
- README.md
- indexdigest/cli/script.py
- indexdigest/linters/__init__.py
- indexdigest/linters/linter_0031_low_cardinality_index.py
- indexdigest/test/__init__.py
- indexdigest/test/linters/test_0031_low_cardinality_index.py
- sql/0020-big-table.sql
> Report low cardinality indices

- Dockerfile
```
$ docker images | head -n2
REPOSITORY                                      TAG                     IMAGE ID            CREATED             SIZE
macbre/index-digest                             1.2.0-408ff58           e84b6980a754        3 minutes ago       255MB
```
Image is smaller then from #150.
> Dockerfile: use python:3.7-slim-buster as a base image

- .pylintrc
- indexdigest/database.py
- indexdigest/test/core/test_utils.py
- indexdigest/utils.py
A small change that allows a non-default port to be specified in the DSN. If it's left out, it will default to 3306.
> Allow port to be specified in DSN

- .travis.yml
It's better to check if the current version builds a Docker image - see #164
> Travis: there's no need to run a demo after each build

- indexdigest/database.py
- indexdigest/linters/linter_0031_low_cardinality_index.py
- indexdigest/test/core/test_database.py
- indexdigest/test/linters/test_0031_low_cardinality_index.py
And fix integration tests
```sql
-- Server version:		8.0.20 MySQL Community Server - GPL
mysql> select TABLE_NAME, INDEX_NAME, COLUMN_NAME, CARDINALITY from INFORMATION_SCHEMA.STATISTICS where table_name = '0020_big_table';
+----------------+------------+-------------+-------------+
| TABLE_NAME     | INDEX_NAME | COLUMN_NAME | CARDINALITY |
+----------------+------------+-------------+-------------+
| 0020_big_table | num_idx    | num         |           2 |
| 0020_big_table | PRIMARY    | item_id     |      100256 |
| 0020_big_table | text_idx   | text        |      100256 |
+----------------+------------+-------------+-------------+
3 rows in set (0.00 sec)
```
vs
```sql
-- Server version:		5.5.5-10.5.4-MariaDB-1:10.5.4+maria~focal mariadb.org binary distribution
mysql> select …
```
> Improve low cardinality indices detection

- .github/workflows/python.yml
- .github/workflows/tests.yml
- Makefile
- indexdigest/test/__init__.py
- indexdigest/test/linters/test_0031_low_cardinality_index.py
Run  `ANALYZE TABLE` after setting up big table for tests.
> For InnoDB tables, `ANALYZE TABLE` determines index cardinality by performing random dives on each of the index trees and updating index cardinality estimates accordingly. Because these are only estimates, repeated runs of `ANALYZE TABLE` could produce different numbers. This makes `ANALYZE TABLE` fast on InnoDB tables but not 100% accurate because it does not take all rows into account.
>
> -- https://dev.mysql.com/doc/refman/8.0/en/analyze-table.html
> Decrease cardinality to stabilize tests

- .github/workflows/dockerimage.yml
See https://testdriven.io/blog/faster-ci-builds-with-docker-cache/
> Use Docker layers cache to speed up CI builds

- .github/workflows/python.yml
- .github/workflows/tests.yml
- README.md
- indexdigest/test/__init__.py
- sql/populate.sh
This will ease a local development in case a local MySQL instance is running on a default port (3306).
> CI | run database on a custom port

- indexdigest/linters/linter_0019_queries_not_using_indices.py
- indexdigest/test/linters/test_0019_queries_not_using_indices.py
- sql/0019-queries-not-using-indices-log
- sql/0019-queries-not-using-indices.sql
Fixes #210 
Ignore "Select tables optimized away":
> The query contained only aggregate functions (MIN(), MAX()) that were all resolved using an index, or COUNT(*) for MyISAM, and no GROUP BY clause. The optimizer determined that only one row should be returned.
And "No matching min/max row" - when the table is simply empty
> Improve queries_not_using_index linter

- .dockerignore
- .github/workflows/dockerimage.yml
- Dockerfile
Despite https://pythonspeed.com/articles/alpine-docker-python/ wheels build takes around 4 seconds.
```
REPOSITORY                                          TAG                       IMAGE ID            CREATED              SIZE
macbre/index-digest                                 latest                    6d8642f9cb92        32 seconds ago       86.8MB
```
vs
```
REPOSITORY                                           TAG         IMAGE ID       CREATED         SIZE
macbre/index-digest                                  latest      27413be31ce3   2 seconds ago   186MB
```
> Docker - use alpine as a base image

- .github/workflows/python.yml
- .github/workflows/tests.yml
- Makefile
- README.md
- setup.py
https://coveralls.io/github/macbre/index-digest
> Send code coverage report to Coveralls
