macbre/index-digest

.travis.yml, README.md, sql/0004-redundant-indices.sql, sql/README.md, sql/populate.sh
=> TravisCI integration

.pylintrc, Makefile, indexdigest/database.py, indexdigest/indices.py, indexdigest/linters/__init__.py, indexdigest/linters/redundant_indices.py, indexdigest/test/__init__.py, indexdigest/test/core/__init__.py, indexdigest/test/core/test_database.py, indexdigest/test/core/test_indices.py, indexdigest/test/linters/test_redundant_indices.py, indexdigest/test/test_0004_redundant_indices.py, sql/0000-core.sql
=> Detect redundant indices

Makefile, README.md, indexdigest/cli/script.py, indexdigest/database.py, indexdigest/linters/__init__.py, indexdigest/linters/not_used_columns_and_tables.py, indexdigest/query.py, indexdigest/test/core/test_query.py, indexdigest/test/core/test_utils.py, indexdigest/test/linters/test_not_used_columns_and_tables.py, indexdigest/utils.py, setup.py, sql/0006-not-used-columns-and-tables-log, sql/0006-not-used-columns-and-tables.sql
=> Report not used columns and tables

indexdigest/cli/script.py, indexdigest/database.py, indexdigest/linters/not_used_columns_and_tables.py, indexdigest/linters/redundant_indices.py, indexdigest/test/core/test_database.py, indexdigest/test/linters/test_not_used_columns_and_tables.py, indexdigest/test/linters/test_redundant_indices.py, sql/0006-not-used-columns-and-tables.sql
=> redundant_indices: show table schema and table / indices size in the context

README.md, indexdigest/cli/script.py, indexdigest/linters/__init__.py, indexdigest/linters/not_used_indices.py, indexdigest/test/linters/test_not_used_indices.py, sql/0002-not-used-indices-log, sql/0002-not-used-indices.sql
=> Report not used indices

indexdigest/cli/script.py, setup.py
=> Color reports

README.md, indexdigest/cli/script.py, indexdigest/linters/__init__.py, indexdigest/linters/not_used_indices.py, indexdigest/test/linters/test_not_used_indices.py, sql/0019-queries-not-using-indices-log, sql/0019-queries-not-using-indices.sql
=> Reports queries that do not use indices

README.md, indexdigest/cli/script.py, indexdigest/linters/__init__.py, indexdigest/linters/filesort_temporary_table.py, indexdigest/linters/not_used_indices.py, indexdigest/test/__init__.py, indexdigest/test/linters/test_0020_big_table.py, indexdigest/utils.py, sql/0020-big-table-log, sql/0020-big-table.sql
=> Report queries that use filesort or temporary file

indexdigest/schema.py, indexdigest/test/core/test_columns.py
=> indexdigest.schema.Column - introduce is_text_type() and is_timestamp_type()

README.md, indexdigest/cli/script.py, indexdigest/linters/__init__.py, indexdigest/linters/linter_0002_not_used_indices.py, indexdigest/linters/linter_0020_filesort_temporary_table.py, indexdigest/linters/linter_0026_full_table_scan.py, indexdigest/test/__init__.py, indexdigest/test/core/test_utils.py, indexdigest/test/linters/test_0026_full_table_scan.py, indexdigest/utils.py, sql/0026-full-table-scan-log
=> Report full table scan

README.md
Not everyone has virtualenv installed ;)
=> Add virtualenv to requirements

README.md
username/password/dbname rather than reusing `index_digest` three times in one string
=> More explicit example of DSN

README.md, indexdigest/cli/script.py, indexdigest/database.py, indexdigest/linters/__init__.py, indexdigest/linters/linter_0032_utf_latin_columns.py, indexdigest/schema.py, indexdigest/test/linters/test_0032_utf_latin_columns.py, sql/0032-utf-latin-columns.sql
=> Report text columns that use non-utf collation

README.md, indexdigest/cli/script.py, indexdigest/linters/__init__.py, indexdigest/linters/linter_0027_selects_with_like.py, indexdigest/test/__init__.py, indexdigest/test/linters/test_0027_selects_with_like.py, sql/0020-big-table.sql, sql/0027-selects-with-like-log
=> Warn on queries which contain wildcards not at the end of LIKE clauses

.travis.yml, Makefile, indexdigest/test/__init__.py, indexdigest/test/core/test_database.py, sql/populate.sh
=> Travis | set up MySQL 5.7 via docker

.travis.yml, README.md, indexdigest/database.py, indexdigest/test/core/test_database.py, indexdigest/test/linters/test_0020_big_table.py, indexdigest/test/test_0004_redundant_indices_core.py, sql/0020-big-table-log
=> Add support for MySQL 8.0

.pylintrc, indexdigest/database.py, indexdigest/linters/linter_0027_selects_with_like.py
=> Suppress MySQL warnings when EXPLAIN is run

indexdigest/cli/script.py, indexdigest/database.py, indexdigest/test/__init__.py, indexdigest/test/core/test_database.py, indexdigest/utils.py
=> Cache database meta-data

.travis.yml, README.md, indexdigest/test/core/test_database.py
=> Add support for MariaDB

Makefile, README.md, indexdigest/cli/script.py, indexdigest/linters/__init__.py, indexdigest/linters/linter_0034_missing_primary_index.py, indexdigest/test/linters/test_0034_missing_primary_index.py, sql/0034-missing-primary-index.sql
=> Check for missing primary or unique keys

.travis.yml, README.md, indexdigest/cli/script.py, indexdigest/formatters/__init__.py, indexdigest/formatters/plain.py, indexdigest/test/formatters/__init__.py, indexdigest/test/formatters/test_plain.py, setup.py
=> Support more formatters

README.md, indexdigest/cli/script.py, indexdigest/formatters/__init__.py, indexdigest/formatters/yaml.py, indexdigest/test/formatters/test_yaml.py, setup.py
=> Add YAML results formatter

README.md, indexdigest/cli/script.py, indexdigest/formatters/__init__.py, indexdigest/formatters/syslog.py, indexdigest/formatters/yaml.py, indexdigest/linters/linter_0002_not_used_indices.py, indexdigest/linters/linter_0004_redundant_indices.py, indexdigest/test/formatters/test_plain.py, indexdigest/test/formatters/test_syslog.py, indexdigest/test/formatters/test_yaml.py
=> Add syslog results reporter

README.md, indexdigest/cli/script.py, indexdigest/linters/__init__.py, indexdigest/linters/linter_0075_test_tables.py, indexdigest/test/linters/test_0075_test_tables.py, sql/0075-test-tables.sql
=> Report tables with "test" word in a name

README.md, indexdigest/cli/script.py, indexdigest/linters/__init__.py, indexdigest/linters/linter_0070_insert_ignore.py, indexdigest/query.py, indexdigest/test/core/test_query.py, indexdigest/test/linters/test_0070_insert_ignore.py, sql/0070-insert-ignore-log, sql/0070-insert-ignore-log.sql
=> Report INSERT IGNORE queries

indexdigest/linters/linter_0070_insert_ignore.py, indexdigest/test/linters/test_0070_insert_ignore.py
=> is_insert_ignore_query: properly detect queries with a whitespace prefix

README.md, indexdigest/cli/script.py, indexdigest/linters/__init__.py, indexdigest/linters/linter_0074_single_column.py, indexdigest/test/linters/test_0074_single_column.py, sql/0006-not-used-columns-and-tables.sql, sql/0074-single-column.sql
=> Report tables with just a single column

indexdigest/formatters/syslog.py, indexdigest/test/formatters/test_syslog.py
This will route our messages to a proper logstash index.
=> syslog: emit appname field

indexdigest/database.py, indexdigest/test/core/test_database.py
=> get_table_schema: cache the results

README.md, indexdigest/cli/add_linter.py, indexdigest/cli/script.py, indexdigest/database.py, indexdigest/linters/__init__.py, indexdigest/linters/linter_0089_empty_tables.py, indexdigest/test/linters/test_0089_empty_tables.py, sql/0089-empty-tables.sql
=> Report empty tables

indexdigest/database.py, indexdigest/linters/linter_0089_empty_tables.py, indexdigest/test/core/test_database.py, indexdigest/test/linters/test_0020_big_table.py
=> empty_tables: use EXPLAIN SELECT count(*) to estimate rows count

indexdigest/database.py, indexdigest/linters/linter_0006_not_used_columns_and_tables.py, indexdigest/test/__init__.py, indexdigest/test/linters/test_0006_not_used_columns_and_tables.py, indexdigest/test/test_0089_handle_sql_errors.py, indexdigest/utils.py, sql/0006-not-used-columns-and-tables-log, sql/0098-handle-sql-errors-log
=> Gracefully handle complex queries that can't be parsed

README.md, indexdigest/cli/script.py, indexdigest/linters/__init__.py, indexdigest/linters/linter_0092_select_star.py, indexdigest/test/linters/test_0092_select_star.py, indexdigest/utils.py, sql/0092-select-star-log
=> Report select queries with *

README.md, indexdigest/cli/script.py, indexdigest/linters/__init__.py, indexdigest/linters/linter_0093_having_clause.py, indexdigest/test/linters/test_0093_having_clause.py, sql/0093-having-clause-log
=> Report queries with HAVING clause

README.md, indexdigest/linters/linter_0006_not_used_columns_and_tables.py, indexdigest/test/linters/test_0006_not_used_columns_and_tables.py, sql/0006-not-used-columns-and-tables.sql
=> not_used_tables: report rows count, table size and its schema

indexdigest/database.py
=> get_table_schema: cast to str

indexdigest/database.py, indexdigest/test/test_0107_schema_partitions.py, sql/0107-schema-partitions.sql
=> Do not add partitions in schema returned by the database helper

Makefile, README.md, indexdigest/cli/script.py, indexdigest/linters/__init__.py, indexdigest/linters/linter_0028_data_too_old.py, indexdigest/test/linters/test_0028_data_too_old.py, sql/0028-data-too-old.sql
=> Add check_data_too_old linter

.pylintrc, README.md, indexdigest/cli/script.py, indexdigest/linters/__init__.py, indexdigest/linters/linter_0028_data_not_updated_recently.py, indexdigest/linters/linter_0028_data_too_old.py, indexdigest/test/linters/test_0028_data_not_updated_recently.py, indexdigest/test/linters/test_0028_data_too_old.py, sql/0028-data-not-updated-recently.sql, sql/0028-data-too-old.sql
=> Add check_data_not_updated_recently linter

indexdigest/linters/linter_0028_data_too_old.py, sql/0002-not-used-indices-log
=> Wrap table names in backticks to fix #112

indexdigest/linters/linter_0028_data_not_updated_recently.py, indexdigest/linters/linter_0028_data_too_old.py
=> check_data_not_updated_recently / check_data_too_old - cast timestamps to str

README.md, indexdigest/linters/linter_0028_data_not_updated_recently.py, indexdigest/linters/linter_0028_data_too_old.py, indexdigest/test/linters/test_0028_data_not_updated_recently.py, indexdigest/test/linters/test_0028_data_too_old.py
=> Data too old more details in report data_too_old / data_not_updated_recently - report timestamp column name and table size

Makefile, README.md, indexdigest/cli/script.py, indexdigest/test/test_script.py
=> Process selected checks when --checks / --skip-checks option is provided

Makefile, README.md, indexdigest/cli/script.py, indexdigest/test/test_script.py
=> Process only selected tables when --tables / --skip-tables option is provided

.travis.yml, README.md, indexdigest/cli/script.py, indexdigest/linters/__init__.py, indexdigest/linters/linter_0118_high_offset_selects.py, indexdigest/test/linters/test_0118_high_offset_selects.py, sql/0118-high-offset-selects-log, wait_for_mysql.sh
=> Avoid high offsets in queries

indexdigest/linters/linter_0075_test_tables.py, indexdigest/test/linters/test_0075_test_tables.py
=> test_tables | identify temporary tables as well

indexdigest/database.py, indexdigest/test/core/test_database.py, sql/0000-core.sql
=> Handle tables names with dashes

indexdigest/database.py, indexdigest/test/core/test_database.py, sql/0000-core.sql
=> Ignore views when checking tables

indexdigest/linters/linter_0028_data_too_old.py, indexdigest/test/linters/test_0028_data_not_updated_recently.py, sql/0028-data-too-old.sql
=> data_too_old | handle incorrect or missing timestamp values

indexdigest/test/core/test_utils.py, indexdigest/test/linters/test_0092_select_star.py, indexdigest/utils.py
=> is_select_query: improve handling of SQL comments

indexdigest/linters/linter_0118_high_offset_selects.py, sql/0118-high-offset-selects-log
=> high_offset_selects: ignore insert queries

README.md, indexdigest/cli/script.py, indexdigest/linters/__init__.py, indexdigest/linters/linter_0036_use_innodb.py, indexdigest/test/linters/test_0036_use_innodb.py, sql/0036-use-innodb.sql
=> Suggest InnoDB over MyISAM

indexdigest/linters/linter_0032_utf_latin_columns.py, indexdigest/test/linters/test_0032_utf_latin_columns.py, sql/0032-utf-latin-columns.sql
=> non_utf_columns | handle blobs and other UTF character sets

.github/workflows/tests.yml, indexdigest/database.py, indexdigest/linters/linter_0020_filesort_temporary_table.py, indexdigest/linters/linter_0026_full_table_scan.py, indexdigest/linters/linter_0027_selects_with_like.py
https://hub.docker.com/_/mariadb
=> Tests: run using MariaDB 10.5.x too

.github/workflows/tests.yml, Dockerfile
https://docs.python.org/3.9/whatsnew/3.9.html
=> Use Python 3.9

.github/workflows/tests.yml
https://github.com/actions/cache/blob/main/examples.md#using-pip-to-get-cache-location
=> CI: cache pip dependencies

.github/workflows/dockerimage.yml
https://docs.docker.com/develop/develop-images/build_enhancements/
=> Try to use Docker's BuildKit

.github/workflows/dockerimage.yml
=> docker build - use --cache-from

.github/workflows/dockerimage.yml, Dockerfile
Resolves #220 
And expose the commit hash to `COMMIT_SHA` env variable
=> Label the image with git URL and commit hash

.dockerignore, .github/workflows/dockerimage.yml, Dockerfile, indexdigest/cli/script.py, setup.py
```
$ COMMIT_SHA=0f3dc4b99ccf1cea0e8c3620e5b36d8507b00e9a index_digest --version
index_digest 1.5.0 (git 0f3dc4b)
```
=> Show commit hash in --version output (when running using Docker container)

.github/workflows/push-to-ghcr.yml
https://github.com/macbre/push-to-ghcr/pull/9
=> Push to docker.io

.github/workflows/python.yml
And update pip hoping to fix https://github.com/pypa/pip/pull/10252
=> CI - use python 3.10.0-rc.1

.github/workflows/tests.yml, indexdigest/test/core/test_database.py
Add:
* mysql:8.1.0
* mariadb:10.6
=> CI - Update the list of MySQL containers
